CREATE TABLE IF NOT EXISTS pokemon (
    id SERIAL PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    treinador VARCHAR(100) NOT NULL,
    nivel INTEGER, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
