CREATE TABLE IF NOT EXISTS pokemon (
    id SERIAL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    trainer VARCHAR(100) NOT NULL,
    level INTEGER, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
